name: Deploy to S3

on:
  push:
    branches:
      - main

env:
  BUCKET_NAME: bulochka
  AWS_REGION: eu-central-1

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::784486495413:role/GithubActionsRole
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-actions-session

      - name: Upload index.html to S3
        run: |
          aws s3 cp ./index.html s3://${{ env.BUCKET_NAME }}/index.html


